/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;


/**
 *
 * @author Luis
 */
public class MenuU extends javax.swing.JFrame {

    /**
     * Creates new form MenuU
     */
    public MenuU() {
        initComponents();
        
        MetodosComboBox.llenarTipoCuenta(comboBoxTipoCuenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fSLabel1 = new LIB.FSLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBanco = new javax.swing.JButton();
        btnFoto = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        PanelVentanas = new javax.swing.JTabbedPane();
        Banco = new javax.swing.JPanel();
        comboBoxMeses = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboBoxTipoCuenta = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        comboBoxMovimiento = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1160, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 255, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 50));

        jLabel6.setText("jLabel3");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 60, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 70));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel5.setText("Bienvenido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 140, 60));

        fSLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajero.png"))); // NOI18N
        fSLabel1.setText("");
        jPanel1.add(fSLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conectado.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, 40));

        btnBanco.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btnBanco.setText("Banco");
        btnBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 230, 40));

        btnFoto.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btnFoto.setText("foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 150, 40));

        btnEditar1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btnEditar1.setText("Editar informacion");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 260, 710));

        Banco.setBackground(new java.awt.Color(102, 255, 153));
        Banco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxMeses.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        comboBoxMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMesesActionPerformed(evt);
            }
        });
        Banco.add(comboBoxMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 190, 40));

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel14.setText("Meses:");
        Banco.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 180, 30));

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel15.setText("Tipo de movimiento:");
        Banco.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 30));

        comboBoxTipoCuenta.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        comboBoxTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoCuentaActionPerformed(evt);
            }
        });
        Banco.add(comboBoxTipoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 190, 40));

        jLabel16.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel16.setText("Tipo de cuenta:");
        Banco.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 180, 30));

        comboBoxMovimiento.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        comboBoxMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir movimiento", "Retiro", "Deposito" }));
        comboBoxMovimiento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxMovimientoItemStateChanged(evt);
            }
        });
        Banco.add(comboBoxMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 200, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Datos de la cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        Banco.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 260, 310));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Banco.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 550, 310));

        PanelVentanas.addTab("tab1", Banco);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jLabel4.setText("Tipo de cuenta:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 39, 290, 32));

        PanelVentanas.addTab("tab2", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        PanelVentanas.addTab("tab3", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        PanelVentanas.addTab("tab4", jPanel5);

        getContentPane().add(PanelVentanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 920, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancoActionPerformed
        PanelVentanas.setSelectedIndex(0);
    }//GEN-LAST:event_btnBancoActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        PanelVentanas.setSelectedIndex(2);

    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        PanelVentanas.setSelectedIndex(1);

    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void comboBoxMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMesesActionPerformed

    private void comboBoxTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoCuentaActionPerformed
        MetodosComboBox.llenarMeses(comboBoxTipoCuenta, comboBoxMeses);
    }//GEN-LAST:event_comboBoxTipoCuentaActionPerformed

    private void comboBoxMovimientoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxMovimientoItemStateChanged
        
        
    }//GEN-LAST:event_comboBoxMovimientoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banco;
    private javax.swing.JTabbedPane PanelVentanas;
    private javax.swing.JButton btnBanco;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnFoto;
    private javax.swing.JComboBox<String> comboBoxMeses;
    private javax.swing.JComboBox<String> comboBoxMovimiento;
    private javax.swing.JComboBox<String> comboBoxTipoCuenta;
    private LIB.FSLabel fSLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
